# Generated by Django 4.2.1 on 2023-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0002_cancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='artistas',
            field=models.CharField(default='valor_predeterminado', max_length=200),
        ),
    ]
