# Generated by Django 4.2.1 on 2023-07-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0004_cancion_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='descripcion',
        ),
    ]
