# Generated by Django 4.2.1 on 2023-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0006_comprobante_detallecomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='canciones',
            field=models.ManyToManyField(to='music_store.cancion'),
        ),
    ]
