# Generated by Django 4.2.1 on 2023-07-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0007_comprobante_canciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecomprobante',
            old_name='nombre',
            new_name='comprobante',
        ),
    ]
